[package]
name = "onuros-orchard-ffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
license-file = "../../LICENSE"
publish = false

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
incrementalmerkletree = "0.8.2"
nonempty = "0.11"
orchard = { git = "https://github.com/zcash/orchard.git", rev = "f2be3a479837df6583110fd44e124d155ec592ee", features = ["test-dependencies"] }
rand = "0.8"
sha2 = "0.10.9"

[dev-dependencies]
proptest = "1.6"
